#! /usr/bin/env bash
#
#
#  athenak animations of 1D problems using NEMO's tabplot 
#
#> ENTRY   base=LinWave    la la
#> RADIO   xcol=x1v       i,x1v,rho,press,vel1,vel2,vel3  
#> RADIO   ycol=vel1      i,x1v,rho,press,vel1,vel2,vel3  

#             set defaults
base=LinWave
xcol=x1v
ycol=vel1

#             simple keyword=value command line parser for bash
for arg in "$@"; do
  export "$arg"
done

#             no NEMO, no go
if [ "$NEMO" == "" ]; then
    echo "Alas, we need some NEMO tools for this"
    exit 0
fi

# we need to translate the column name to the column number.....
# a bash contortion
tmp=/tmp/tmp.log
f0=$(ls ${base}*tab | head -1)
for i in $(tabrows $f0 2); do echo $i; done | awk '{print NR-1,$1}' > $tmp
ixcol=$(grep -w $xcol $tmp | awk '{print $1}')
iycol=$(grep -w $ycol $tmp | awk '{print $1}')


for f in ${base}*tab; do
    tabplot $f xcol=$ixcol ycol=$iycol xlab=$xcol ylab=$ycol
done

echo -n "DEBUG: "
tabrows $f0 2
echo "DEBUG: xcol=$ixcol ($xcol) ycol=$iycol ($ycol)"
