#!/bin/csh
#
#>  IFILE   in= 
#>  OFILE   out= 
#>  IDIR    indir= 
#>  ENTRY   eps=0.01
#>  RADIO   mode=gauss              gauss,newton,leibniz
#>  CHECK   options=mean,sigma      sum,mean,sigma,skewness,kurtosis
#>  ENTRY   txt=200
#>  RADIO   buttons=1               1,2,3,4,5
#>  RADIO   buttons=1               1,2,3,4,5
#>  CHECK   choose=1,5              1,2,3,4,5
#>  ENTRY   txt=200
#>  RADIO   buttons=1               1,2,3,4,5
#>  RADIO   buttons=1               1,2,3,4,5
#>  CHECK   choose=1                 1,2,3,4
#>  CHECK   choose=2                1,2
#>  RADIO   buttons=1               1,2,3,4,5
#>  RADIO   buttons=1               1,2,3,4,5
#>  RADIO   buttons=1               1,2,3,4,5
#>  RADIO   buttons=1               1,2,3,4,5
#>  RADIO   buttons=1               1,2,3,4,5
#>  RADIO   buttons=1               1,2,3,4,5
#>  SCALE   n=20            0:50:0.1